"""Tests for application logging buffer and models."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

from backend.api.app_logging import (
    AppLogEntry,
    ClientErrorReport,
    LogBuffer,
    get_app_log_buffer,
    log_client_error,
    log_request_error,
)

# ---------------------------------------------------------------------------
# Model Tests
# ---------------------------------------------------------------------------


def test_app_log_entry_model():
    """Verify AppLogEntry model validation and serialization."""
    entry = AppLogEntry(
        timestamp="2024-01-15T10:30:00Z",
        level="info",
        message="Test message",
        data={"key": "value"},
    )
    assert entry.timestamp == "2024-01-15T10:30:00Z"
    assert entry.level == "info"
    assert entry.message == "Test message"
    assert entry.data == {"key": "value"}


def test_app_log_entry_optional_data():
    """Verify AppLogEntry with no data field."""
    entry = AppLogEntry(timestamp="2024-01-15T10:30:00Z", level="warn", message="Warning message")
    assert entry.data is None


def test_client_error_report_model():
    """Verify ClientErrorReport model validation."""
    report = ClientErrorReport(
        error_type="TypeError",
        message="Cannot read property 'x' of undefined",
        stack="at Component.render (app.tsx:42)",
        user_agent="Mozilla/5.0",
        url="https://example.com/app",
        context={"component": "DataTable"},
    )
    assert report.error_type == "TypeError"
    assert report.message == "Cannot read property 'x' of undefined"
    assert report.stack is not None
    assert report.user_agent == "Mozilla/5.0"
    assert report.context == {"component": "DataTable"}


def test_client_error_report_minimal():
    """Verify ClientErrorReport with only required fields."""
    report = ClientErrorReport(error_type="Error", message="Something went wrong")
    assert report.error_type == "Error"
    assert report.message == "Something went wrong"
    assert report.stack is None
    assert report.user_agent is None
    assert report.url is None
    assert report.context is None


# ---------------------------------------------------------------------------
# LogBuffer Tests
# ---------------------------------------------------------------------------


def test_log_buffer_basic_logging():
    """Verify basic log entry addition and retrieval."""
    buffer = LogBuffer(max_size=10)
    buffer.log("info", "Test message", {"key": "value"})

    entries = buffer.get_recent(limit=10)
    assert len(entries) == 1
    assert entries[0].level == "info"
    assert entries[0].message == "Test message"
    assert entries[0].data == {"key": "value"}


def test_log_buffer_convenience_methods():
    """Verify convenience methods (debug, info, warn, error)."""
    buffer = LogBuffer(max_size=10)
    buffer.debug("Debug message")
    buffer.info("Info message")
    buffer.warn("Warning message")
    buffer.error("Error message")

    entries = buffer.get_recent(limit=10)
    assert len(entries) == 4
    assert entries[0].level == "debug"
    assert entries[1].level == "info"
    assert entries[2].level == "warn"
    assert entries[3].level == "error"


def test_log_buffer_max_size_eviction():
    """Verify oldest entries are evicted when buffer is full."""
    buffer = LogBuffer(max_size=3)
    buffer.info("Entry 1")
    buffer.info("Entry 2")
    buffer.info("Entry 3")
    buffer.info("Entry 4")  # Should evict Entry 1

    entries = buffer.get_recent(limit=10)
    assert len(entries) == 3
    assert entries[0].message == "Entry 2"
    assert entries[1].message == "Entry 3"
    assert entries[2].message == "Entry 4"


def test_log_buffer_filter_by_level():
    """Verify level filtering in get_recent()."""
    buffer = LogBuffer(max_size=10)
    buffer.debug("Debug 1")
    buffer.info("Info 1")
    buffer.warn("Warn 1")
    buffer.error("Error 1")
    buffer.info("Info 2")

    info_entries = buffer.get_recent(limit=10, level="info")
    assert len(info_entries) == 2
    assert all(e.level == "info" for e in info_entries)

    error_entries = buffer.get_recent(limit=10, level="error")
    assert len(error_entries) == 1
    assert error_entries[0].message == "Error 1"


def test_log_buffer_filter_by_time():
    """Verify time-based filtering in get_recent()."""
    buffer = LogBuffer(max_size=10)

    # Create entries with timestamps 5 minutes apart
    now = datetime.now(UTC)
    cutoff_time = (now - timedelta(minutes=2)).isoformat()

    buffer.info("Old entry")
    # Manually adjust timestamp for testing
    buffer._buffer[-1].timestamp = (now - timedelta(minutes=5)).isoformat()

    buffer.info("Recent entry")
    # This entry timestamp is generated by log() and will be current

    recent_entries = buffer.get_recent(limit=10, since=cutoff_time)
    assert len(recent_entries) == 1
    assert recent_entries[0].message == "Recent entry"


def test_log_buffer_limit():
    """Verify limit parameter restricts number of returned entries."""
    buffer = LogBuffer(max_size=100)
    for i in range(20):
        buffer.info(f"Entry {i}")

    entries = buffer.get_recent(limit=5)
    assert len(entries) == 5
    # Should return most recent 5 entries
    assert entries[0].message == "Entry 15"
    assert entries[4].message == "Entry 19"


def test_log_buffer_clear():
    """Verify clear() removes all entries."""
    buffer = LogBuffer(max_size=10)
    buffer.info("Entry 1")
    buffer.info("Entry 2")
    buffer.info("Entry 3")

    assert buffer.size() == 3
    buffer.clear()
    assert buffer.size() == 0


def test_log_buffer_size():
    """Verify size() returns correct count."""
    buffer = LogBuffer(max_size=10)
    assert buffer.size() == 0

    buffer.info("Entry 1")
    assert buffer.size() == 1

    buffer.info("Entry 2")
    buffer.info("Entry 3")
    assert buffer.size() == 3


def test_log_buffer_timestamps():
    """Verify timestamps are ISO 8601 with timezone."""
    buffer = LogBuffer(max_size=10)
    buffer.info("Test entry")

    entries = buffer.get_recent(limit=1)
    timestamp = entries[0].timestamp

    # Should parse as ISO 8601
    parsed = datetime.fromisoformat(timestamp)
    assert parsed.tzinfo is not None  # Timezone must be present


# ---------------------------------------------------------------------------
# Global Instance Tests
# ---------------------------------------------------------------------------


def test_get_app_log_buffer_singleton():
    """Verify get_app_log_buffer() returns singleton instance."""
    buffer1 = get_app_log_buffer()
    buffer2 = get_app_log_buffer()
    assert buffer1 is buffer2


# ---------------------------------------------------------------------------
# Convenience Function Tests
# ---------------------------------------------------------------------------


def test_log_request_error():
    """Verify log_request_error() logs with structured context."""
    buffer = get_app_log_buffer()

    log_request_error(
        request_id="req-123",
        endpoint="/api/v2/data",
        error_category="network_policy",
        message="IP not allowed",
    )

    entries = buffer.get_recent(limit=1)
    assert len(entries) == 1
    assert entries[0].level == "error"
    assert "Request failed" in entries[0].message
    assert entries[0].data is not None
    assert entries[0].data["request_id"] == "req-123"
    assert entries[0].data["endpoint"] == "/api/v2/data"
    assert entries[0].data["category"] == "network_policy"


def test_log_client_error():
    """Verify log_client_error() logs client error reports."""
    buffer = get_app_log_buffer()

    report = ClientErrorReport(
        error_type="TypeError",
        message="Cannot access property",
        stack="at render()",
        url="https://example.com/app",
        user_agent="Mozilla/5.0",
        context={"component": "DataTable"},
    )

    log_client_error(report, request_id="req-456")

    entries = buffer.get_recent(limit=1)
    assert len(entries) == 1
    assert entries[0].level == "error"
    assert "Client error: TypeError" in entries[0].message
    assert entries[0].data is not None
    assert entries[0].data["request_id"] == "req-456"
    assert entries[0].data["error_type"] == "TypeError"
    assert entries[0].data["url"] == "https://example.com/app"
