-- ============================================================================
-- Retail Data Harmonization Demo
-- Script: sql/setup/05_seed_data/05i_raw_items_stadium.sql
-- Purpose: Generate 1000+ POS_STADIUM records using realistic naming patterns
-- ============================================================================
--
-- POS_STADIUM Characteristics:
-- - ALL-CAPS abbreviated descriptions (typical stadium POS style)
-- - Common abbreviations: 20OZ, 16OZ, LG, REG, etc.
-- - High transaction volumes typical of stadium events
-- - Realistic product variations and misspellings
-- ============================================================================

USE ROLE HARMONIZER_DEMO_ROLE;
USE DATABASE HARMONIZER_DEMO;
USE WAREHOUSE HARMONIZER_DEMO_WH;

INSERT INTO HARMONIZER_DEMO.RAW.RAW_RETAIL_ITEMS 
    (ITEM_ID, RAW_DESCRIPTION, SOURCE_SYSTEM, SOURCE_ITEM_CODE, EVENT_ID, TRANSACTION_COUNT, TRANSACTION_DATE, REGISTER_ID, MATCH_STATUS)
SELECT 
    UUID_STRING(),
    CASE MOD(SEQ4(), 150)
        -- Hot Dogs (0-9)
        WHEN 0 THEN 'HOT DOG REG'
        WHEN 1 THEN 'HOTDOG'
        WHEN 2 THEN 'JUMBO HOT DOG'
        WHEN 3 THEN 'JUMBO HOTDOG'
        WHEN 4 THEN 'ALL BEEF HOT DOG'
        WHEN 5 THEN 'FOOTLONG HOT DOG'
        WHEN 6 THEN 'POLISH SAUSAGE'
        WHEN 7 THEN 'BRATWURST'
        WHEN 8 THEN 'CHILI CHEESE DOG'
        WHEN 9 THEN 'CORN DOG'
        -- Coca-Cola Products (10-19)
        WHEN 10 THEN 'COKE 20OZ'
        WHEN 11 THEN 'COCA COLA 20OZ'
        WHEN 12 THEN 'DIET COKE 20OZ'
        WHEN 13 THEN 'DT COKE 20OZ'
        WHEN 14 THEN 'COKE ZERO 20OZ'
        WHEN 15 THEN 'CHERRY COKE 20OZ'
        WHEN 16 THEN 'COKE 32OZ'
        WHEN 17 THEN 'LARGE COKE'
        WHEN 18 THEN 'COKE CLASSIC 20OZ'
        WHEN 19 THEN 'VANILLA COKE 20OZ'
        -- Other Sodas (20-29)
        WHEN 20 THEN 'SPRITE 20OZ'
        WHEN 21 THEN 'PEPSI 20OZ'
        WHEN 22 THEN 'DIET PEPSI 20OZ'
        WHEN 23 THEN 'MTN DEW 20OZ'
        WHEN 24 THEN 'MOUNTAIN DEW 20OZ'
        WHEN 25 THEN 'DR PEPPER 20OZ'
        WHEN 26 THEN 'ROOT BEER 20OZ'
        WHEN 27 THEN 'FANTA ORANGE 20OZ'
        WHEN 28 THEN '7UP 20OZ'
        WHEN 29 THEN 'GINGER ALE 20OZ'
        -- Domestic Beer (30-39)
        WHEN 30 THEN 'BUD LIGHT 16OZ'
        WHEN 31 THEN 'BUD LT 16OZ'
        WHEN 32 THEN 'BUDWEISER 16OZ'
        WHEN 33 THEN 'BUD LIGHT 24OZ'
        WHEN 34 THEN 'MICHELOB ULTRA 16OZ'
        WHEN 35 THEN 'MICH ULTRA 16OZ'
        WHEN 36 THEN 'MILLER LITE 16OZ'
        WHEN 37 THEN 'COORS LIGHT 16OZ'
        WHEN 38 THEN 'COORS LT 16OZ'
        WHEN 39 THEN 'NATURAL LIGHT 16OZ'
        -- Import/Craft Beer (40-49)
        WHEN 40 THEN 'CORONA 12OZ'
        WHEN 41 THEN 'CORONA EXTRA 12OZ'
        WHEN 42 THEN 'MODELO ESPECIAL 12OZ'
        WHEN 43 THEN 'HEINEKEN 12OZ'
        WHEN 44 THEN 'STELLA ARTOIS 12OZ'
        WHEN 45 THEN 'BLUE MOON 16OZ'
        WHEN 46 THEN 'SAM ADAMS 12OZ'
        WHEN 47 THEN 'DOS EQUIS 12OZ'
        WHEN 48 THEN 'PACIFICO 12OZ'
        WHEN 49 THEN 'GUINNESS 16OZ'
        -- Hard Seltzer (50-54)
        WHEN 50 THEN 'WHITE CLAW 12OZ'
        WHEN 51 THEN 'WHITE CLAW MANGO'
        WHEN 52 THEN 'TRULY SELTZER 12OZ'
        WHEN 53 THEN 'HIGH NOON SELTZER'
        WHEN 54 THEN 'BON VIVI SELTZER'
        -- Chips/Potato Chips (55-69)
        WHEN 55 THEN 'LAYS CLASSIC'
        WHEN 56 THEN 'LAYS CHIPS'
        WHEN 57 THEN 'LAYS POTATO CHIPS'
        WHEN 58 THEN 'LAYS BBQ'
        WHEN 59 THEN 'LAYS SOUR CREAM ONION'
        WHEN 60 THEN 'DORITOS NACHO'
        WHEN 61 THEN 'DORITOS NACHO CHEESE'
        WHEN 62 THEN 'DORITOS COOL RANCH'
        WHEN 63 THEN 'CHEETOS CRUNCHY'
        WHEN 64 THEN 'CHEETOS FLAMIN HOT'
        WHEN 65 THEN 'FRITOS ORIGINAL'
        WHEN 66 THEN 'FRITOS CORN CHIPS'
        WHEN 67 THEN 'RUFFLES CHEDDAR'
        WHEN 68 THEN 'TOSTITOS CHIPS'
        WHEN 69 THEN 'PRINGLES ORIGINAL'
        -- Nachos and Fries (70-79)
        WHEN 70 THEN 'NACHOS CHEESE'
        WHEN 71 THEN 'NACHOS W CHEESE'
        WHEN 72 THEN 'LOADED NACHOS'
        WHEN 73 THEN 'LARGE FRIES'
        WHEN 74 THEN 'LRG FRIES'
        WHEN 75 THEN 'MEDIUM FRIES'
        WHEN 76 THEN 'CURLY FRIES'
        WHEN 77 THEN 'ONION RINGS'
        WHEN 78 THEN 'TATER TOTS'
        WHEN 79 THEN 'LOADED FRIES'
        -- Pretzels and Popcorn (80-86)
        WHEN 80 THEN 'SOFT PRETZEL'
        WHEN 81 THEN 'PRETZEL W CHEESE'
        WHEN 82 THEN 'PRETZEL BITES'
        WHEN 83 THEN 'POPCORN LARGE'
        WHEN 84 THEN 'POPCORN LG'
        WHEN 85 THEN 'POPCORN SMALL'
        WHEN 86 THEN 'KETTLE CORN'
        -- Pizza (87-93)
        WHEN 87 THEN 'PEPPERONI PIZZA SLICE'
        WHEN 88 THEN 'PEPPERONI SLICE'
        WHEN 89 THEN 'CHEESE PIZZA SLICE'
        WHEN 90 THEN 'CHEESE SLICE'
        WHEN 91 THEN 'SUPREME PIZZA SLICE'
        WHEN 92 THEN 'BBQ CHICKEN PIZZA'
        WHEN 93 THEN 'MEAT LOVERS SLICE'
        -- Burgers (94-100)
        WHEN 94 THEN 'CHEESEBURGER'
        WHEN 95 THEN 'BACON CHEESEBURGER'
        WHEN 96 THEN 'DOUBLE CHEESEBURGER'
        WHEN 97 THEN 'HAMBURGER'
        WHEN 98 THEN 'VEGGIE BURGER'
        WHEN 99 THEN 'BBQ BURGER'
        WHEN 100 THEN 'MUSHROOM SWISS BURGER'
        -- Chicken (101-107)
        WHEN 101 THEN 'CHICKEN TENDERS 4PC'
        WHEN 102 THEN 'CHKN TENDERS 6PC'
        WHEN 103 THEN 'CHICKEN SANDWICH'
        WHEN 104 THEN 'CHICKEN WINGS 6PC'
        WHEN 105 THEN 'BUFFALO WINGS'
        WHEN 106 THEN 'CHICKEN NUGGETS 6PC'
        WHEN 107 THEN 'SPICY CHICKEN SAND'
        -- Water (108-112)
        WHEN 108 THEN 'DASANI 20OZ'
        WHEN 109 THEN 'AQUAFINA 20OZ'
        WHEN 110 THEN 'SMARTWATER 20OZ'
        WHEN 111 THEN 'EVIAN WATER'
        WHEN 112 THEN 'BOTTLED WATER'
        -- Energy/Sports Drinks (113-120)
        WHEN 113 THEN 'RED BULL 12OZ'
        WHEN 114 THEN 'MONSTER 16OZ'
        WHEN 115 THEN 'MONSTER ENERGY 16OZ'
        WHEN 116 THEN 'GATORADE ORANGE'
        WHEN 117 THEN 'GATORADE FRUIT PUNCH'
        WHEN 118 THEN 'GATORADE LEMON LIME'
        WHEN 119 THEN 'POWERADE BLUE'
        WHEN 120 THEN 'CELSIUS ENERGY'
        -- Candy Bars (121-132)
        WHEN 121 THEN 'SNICKERS'
        WHEN 122 THEN 'SNICKERS BAR'
        WHEN 123 THEN 'M&M PEANUT'
        WHEN 124 THEN 'M&M PLAIN'
        WHEN 125 THEN 'REESES CUPS'
        WHEN 126 THEN 'KIT KAT'
        WHEN 127 THEN 'TWIX'
        WHEN 128 THEN 'MILKY WAY'
        WHEN 129 THEN 'BUTTERFINGER'
        WHEN 130 THEN 'SKITTLES'
        WHEN 131 THEN 'STARBURST'
        WHEN 132 THEN 'SOUR PATCH KIDS'
        -- Ice Cream (133-139)
        WHEN 133 THEN 'ICE CREAM SUNDAE'
        WHEN 134 THEN 'ICE CREAM CONE'
        WHEN 135 THEN 'SOFT SERVE VANILLA'
        WHEN 136 THEN 'SOFT SERVE CHOC'
        WHEN 137 THEN 'ICE CREAM SANDWICH'
        WHEN 138 THEN 'FROZEN LEMONADE'
        WHEN 139 THEN 'DIPPIN DOTS'
        -- Stadium Classics (140-149)
        WHEN 140 THEN 'PEANUTS BAG'
        WHEN 141 THEN 'CRACKER JACK'
        WHEN 142 THEN 'COTTON CANDY'
        WHEN 143 THEN 'FUNNEL CAKE'
        WHEN 144 THEN 'CHURRO'
        WHEN 145 THEN 'COOKIE'
        WHEN 146 THEN 'BROWNIE'
        WHEN 147 THEN 'LEMONADE LG'
        WHEN 148 THEN 'ICED TEA 20OZ'
        ELSE 'COFFEE LG'
    END AS RAW_DESC,
    'POS_STADIUM',
    'STD-' || LPAD(MOD(SEQ4(), 100)::VARCHAR, 3, '0'),
    'EVT-STD-' || LPAD((MOD(SEQ4(), 35) + 1)::VARCHAR, 3, '0'),
    UNIFORM(100, 3000, RANDOM()),
    DATEADD(day, MOD(SEQ4(), 200), '2025-08-01')::DATE,
    'REG-' || LPAD((MOD(SEQ4(), 20) + 100)::VARCHAR, 3, '0'),
    'PENDING'
FROM TABLE(GENERATOR(ROWCOUNT => 1500));
