-- ============================================================================
-- Retail Data Harmonization Demo
-- Script: sql/setup/01_roles_and_warehouse.sql
-- Purpose: Database, schemas, warehouse, and role setup
-- ============================================================================

USE ROLE SYSADMIN;

-- Database
CREATE DATABASE IF NOT EXISTS HARMONIZER_DEMO
    COMMENT = 'Retail Data Harmonization - POC Demo';

-- Schemas
CREATE SCHEMA IF NOT EXISTS HARMONIZER_DEMO.RAW
    COMMENT = 'Raw ingested data: master items and unmapped retail items';
CREATE SCHEMA IF NOT EXISTS HARMONIZER_DEMO.HARMONIZED
    COMMENT = 'Harmonized matching results and candidates';
CREATE SCHEMA IF NOT EXISTS HARMONIZER_DEMO.ANALYTICS
    COMMENT = 'Analytics, audit logs, and configuration';

-- Warehouse (multi-cluster GEN 2 for parallel pipeline execution)
CREATE WAREHOUSE IF NOT EXISTS HARMONIZER_DEMO_WH
    WAREHOUSE_TYPE = 'STANDARD'
    WAREHOUSE_SIZE = 'MEDIUM'
    RESOURCE_CONSTRAINT = 'STANDARD_GEN_2'
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 3
    SCALING_POLICY = 'STANDARD'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Multi-cluster GEN 2 compute for Retail demo matching pipeline';

USE ROLE SECURITYADMIN;

-- Role
CREATE ROLE IF NOT EXISTS HARMONIZER_DEMO_ROLE
    COMMENT = 'Role for Retail demo users';

-- Grants
GRANT USAGE ON DATABASE HARMONIZER_DEMO TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON SCHEMA HARMONIZER_DEMO.RAW TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON SCHEMA HARMONIZER_DEMO.HARMONIZED TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON SCHEMA HARMONIZER_DEMO.ANALYTICS TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA HARMONIZER_DEMO.RAW TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA HARMONIZER_DEMO.HARMONIZED TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA HARMONIZER_DEMO.ANALYTICS TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA HARMONIZER_DEMO.RAW TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA HARMONIZER_DEMO.HARMONIZED TO ROLE HARMONIZER_DEMO_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA HARMONIZER_DEMO.ANALYTICS TO ROLE HARMONIZER_DEMO_ROLE;
GRANT USAGE ON WAREHOUSE HARMONIZER_DEMO_WH TO ROLE HARMONIZER_DEMO_ROLE;
GRANT OPERATE ON WAREHOUSE HARMONIZER_DEMO_WH TO ROLE HARMONIZER_DEMO_ROLE;

-- Cortex access
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE HARMONIZER_DEMO_ROLE;

-- Grant role to SYSADMIN for hierarchy
GRANT ROLE HARMONIZER_DEMO_ROLE TO ROLE SYSADMIN;

-- Grant role to the user executing this script (dynamic based on connection)
SET current_username = (SELECT CURRENT_USER());
GRANT ROLE HARMONIZER_DEMO_ROLE TO USER IDENTIFIER($current_username);

USE ROLE SYSADMIN;
USE DATABASE HARMONIZER_DEMO;
USE WAREHOUSE HARMONIZER_DEMO_WH;
